### ISSUE TITLE
GetSelection gibt falschen Wert zurück

### ISSUE THREAD

**Issue by LitzeYT** [nyfrk/S4ModApi#10]
Bei GetSelection gibt der Dritte Parameter den Falschen Wert zurück. 

Als ich versuchte das SelectionPlugin zu Überarbeiten bekam ich folgende Fehler : 
Mir wurde der Wert  3435973836  geliefert obwohl ich nur 250 Soldaten makieren wollte.
SendWarriors räumt scheinbar den Stack Falsch auf.
Dabei habe ich einen ESP Check Fehler bekommen.

Mit der neusten Version der ModAPI(direkt vom Master Branch)

**Comment by nyfrk** [comment]
Should work now with version 2.0
