### ISSUE TITLE
Missing functions from my branch  

### ISSUE THREAD

**Issue by WizzardMaker** [nyfrk/S4ModApi#21]
The `AddGuiElementBltListener` seems to be missing from the latest version of the header files?

Reference: https://github.com/WizzardMaker/S4ModApi/blob/76eeb55e976be3f2921f71748f90da1ecb81d441/S4ModApi/S4ModApi.h#L811
https://github.com/WizzardMaker/S4ModApi/blob/76eeb55e976be3f2921f71748f90da1ecb81d441/S4ModApi/CSettlers4Api.h#L50

**Comment by nyfrk** [comment]
Sorry that was not on purpose. I got confused by the revert. I readded it to the end of the vtable of the current interface so compiled plugins against version 2.x stay compatible. Let me know if there is anything else missing.
