### ISSUE TITLE
Skip Update Rename File Name

### ISSUE THREAD

**Issue by kdsystem1337** [nyfrk/S4ModApi#22]
We use Settlers United to check the SHA of the ModApi version closely, as we have to check/apply updates manually. 

The name and location of the file to skip updates is not very well chosen. Could we additionally check if the file "S4ModApiNoUpdate[.cfg]" is there?

**Comment by nyfrk** [comment]
Sure. The auto update feature is more intended for people that do not get the s4modapi.dll via third party vendors. The relevant code that enables to skip it can be found [here](https://github.com/nyfrk/S4ModApi/blob/master/S4ModApi/CUpdate.cpp#L47). 

Feel free to submit a PR.

**Comment by kdsystem1337** [comment]
Is implemented. Committed it instead of requesting it. Hope this is ok.

**Comment by nyfrk** [comment]
Awesome. Thank you. I restructured the IsSkipUpdate function a little to make it more readable. (https://github.com/nyfrk/S4ModApi/commit/10881ec4688213cb1dc01ab5cd52ec24c1ac7124)
