### ISSUE TITLE
Debug Symbols of version 2.3

### ISSUE THREAD

**Issue by WizzardMaker** [nyfrk/S4ModApi#23]
Hey, do you still have the debug symbols for release 2.3? They seem to be missing from the release files

**Comment by nyfrk** [comment]
Sure, I have them. I usually don't bundle them along with the release. However here you go: [S4ModApi_Symbols_2_3.zip](https://github.com/nyfrk/S4ModApi/files/8056814/S4ModApi_Symbols_2_3.zip)
