### ISSUE TITLE
Missing options to get the current player faction

### ISSUE THREAD

**Issue by WizzardMaker** [nyfrk/S4ModApi#3]
Is there a way to get the current player faction (For hotkeys, to know what special food buildings should be placed)?

**Comment by nyfrk** [comment]
I added a function to retrieve the tribe of a player. Use [ISettlers4Api::GetPlayerTribe](https://github.com/nyfrk/S4ModApi/wiki/GetPlayerTribe) and pass 0 for the local players tribe. It is currently only supported by the history edition with md5 C13883CBD796C614365AB2D670EAD561.
